var PUZZLE_HEIGHT=8,PUZZLE_WIDTH=8,DEBUG=false,marka=true,markn=true,board,solution,doRender=true,doMoves=false,found=false,animate=false,debughtml="",greedy=false,autosolve=false,won=false,EDIT=false,key,undo;function keydown(a){if(a&&a.keyCode)key=a.keyCode}function keyup(a){a=a.ctrlKey;key==90&&a&&undoMove();key=null}var isCtrl=false;document.onkeydown=function(a){if(!a)a=window.event;if(a&&a.keyCode)key=a.keyCode;if(key==17)isCtrl=true;key==90&&isCtrl&&undoMove()};
document.onkeyup=function(a){if(!a)a=window.event;if(a&&a.keyCode)key=a.keyCode;if(key==17)isCtrl=false;key=null};var cycle=[0,10,5],cycleEdit=[0,5,1,2,3,4,6,7,8,9,10,11,12,13];function get(a,c){var e=board[a][c];if(e<=10)return"";return e}
function cellFor(a,c){var e=board[a][c],f="s"+e,g=new StringBuffer,h=new StringBuffer;if(e!=5&&e>0&&e<10){g.append("path(");g.append(a);g.append(", ");g.append(c);g.append(", true); pressDown(");g.append(a);g.append(", ");g.append(c);g.append(", ");g.append(e);g.append(");");h.append("path(");h.append(a);h.append(", ");h.append(c);h.append(", false); pressUp(");h.append(a);h.append(", ");h.append(c);h.append(", ");h.append(e);h.append(");")}html=new StringBuffer;html.append('<div id="r');html.append(a);
html.append("c");html.append(c);html.append('" onmousedown="');html.append(g.toString());html.append('" onmouseup="');html.append(h.toString());html.append('" onmouseover="" onmouseout="" onclick="toggle(');html.append(a);html.append(", ");html.append(c);html.append(')" class="');html.append(f);html.append('">');html.append(get(a,c));html.append("</div>");return html.toString()}function renderCell(a,c){d("tr"+a+"c"+c).innerHTML=cellFor(a,c)}
function render(){if(doRender)if(!autosolve){var a=d("board"),c=new StringBuffer;c.append('<table class="board">');for(var e=board.length,f=board[0].length,g=0;g<e;g++){for(var h=0;h<f;h++){val=board[g][h];if(h==0&&g==0)c.append('<td class="corner" style="border: 2px solid white; border-right: 2px solid #ccc; border-bottom: 2px solid #ccc">&nbsp;</td>');else if(h==0){c.append('<td id="r');c.append(g);c.append('" class="c');c.append(val);c.append('" onclick="fill(');c.append(g);c.append(", ");c.append(h);
c.append(', true)" onmouseover="path(');c.append(g);c.append(", ");c.append(h);c.append(', true)" onmouseout="path(');c.append(g);c.append(", ");c.append(h);c.append(', false)" ></td>')}else if(g==0){c.append('<td id="c');c.append(h);c.append('" class="c');c.append(val);c.append('" onclick="fill(');c.append(g);c.append(", ");c.append(h);c.append(', false)" onmouseover="path(');c.append(g);c.append(", ");c.append(h);c.append(', true)" onmouseout="path(');c.append(g);c.append(", ");c.append(h);c.append(', false)" ></td>')}else{c.append('<td id="tr');
c.append(g);c.append("c");c.append(h);c.append('">');c.append(cellFor(g,h));c.append("</td>")}}c.append("</tr>")}c.append("</table>");c.append('<div class="diff"><div id="warn"></div>Difficulty: ');e=Math.round(difficulties[currentBoard]*100);f=difficultyName2()=="Easy"?"green":difficultyName2()=="Medium"?"yellow":"red";c.append('<img src="progressbar.gif" width="120" style="width: 120px; height: 12px; background-image: url(progressbg_'+f+".gif); padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; background-position: -"+
(100-e)+'px 50%; "> <i>'+e+"% ("+difficultyName2()+")</i></div>");c.append('<table><tr valign="middle"><td>');c.append('<a href="javascript:firstPuzzle()"><img border="0" src="first.gif"></a> <a href="javascript:prevPuzzle()"><img border="0" src="previous.gif"></a> </td>');c.append('<td><select name="puzselect" onchange="changepuz()">');e=puzzles[currentDifficulty].length;for(f=0;f<puzzles[currentDifficulty].length;f++){g="";if(f==currentBoard)g=' selected="yes"';c.append("<option"+g+">Puzzle #"+
(f+1)+" of "+e+"</option>")}c.append("</select></td>");c.append('<td><a href="javascript:nextPuzzle()"><img border="0" src="next.gif"></a> <a href="javascript:lastPuzzle()"><img border="0" src="last.gif"></a>');c.append('</td></tr><tr><td colspan="3"><center><a href="javascript:undoMove()">Undo</a> | <a href="javascript:newGameRandom(0)">Random</a> | <a href="javascript:reset()">Reset</a> | <a href="javascript:options()">Options</a> | <a href="javascript:help()">Help</a><br/><a href="http://www.playshinro.com"><em>Back to PlayShinro.com</em></a></center>');
c.append("</td></tr></table>");c.append('<center><div id="options" style="display: none"><input type="checkbox" name="marka" onchange="markaChange()"> Mark satisfied arrows <input type="checkbox" name="markn" onchange="marknChange()"> Mark satisfied row/column counts <a href="javascript:optionsClose()"><em>(Close)</em></a></div></center>');replaceHtml(a,c.toString());markn&&satNAll();EDIT&&showCon()}}function pressDown(a,c,e){d("r"+a+"c"+c).className="pd"+e}
function pressUp(a,c,e){d("r"+a+"c"+c).className="s"+e}function showCon(){for(var a='<input type="text" size="100" value="[',c=1;c<board.length;c++){a+="[";for(var e=1;e<board.length;e++){a+=board[c][e];if(e!=board[0].length-1)a+=","}a+="]";if(c!=board.length-1)a+=",";a+=""}a+='],">';d("con").innerHTML=a}function reveal(){for(var a=0;a<solution.length;a++)for(var c=0;c<solution[0].length;c++)board[a+1][c+1]=solution[a][c];render()}
function reset(){eraseCookie("board");newGame(puzzles[currentDifficulty][currentBoard])}function fill(a,c,e){if(!(animate||blinking)){found=false;fillSquare(a,c,e,false);found||fillSquare(a,c,e,true);render();updateArrows(false);findMoves();checkWin()}}
function fillSquare(a,c,e,f){if(!(a>=board.length))if(!(c>=board[0].length)){if(!(a==0||c==0)){v1=f?10:0;v2=f?0:10;if(board[a][c]==v1){board[a][c]=v2;undo.push([a,c,f?1:-1]);found=true;arrowsItemsUpdate(v1,v2,a,c);updateArrows(false,a,c)}}fillSquare(a+(e?0:1),c+(e?1:0),e,f)}}function path(a,c,e){if(!(animate||blinking)){var f=inc(a,c),g=f[0];f=f[1];if(a==0)a++;else c==0&&c++;flip(a,c,g,f,e)}}
function inc(a,c){var e=[0,0];if(a==0){e[0]=1;e[1]=0}else if(c==0){e[0]=0;e[1]=1}else if(board[a][c]==1){e[0]=1;e[1]=-1}else if(board[a][c]==2){e[0]=1;e[1]=0}else if(board[a][c]==3){e[0]=1;e[1]=1}else if(board[a][c]==4){e[0]=0;e[1]=-1}else if(board[a][c]==6){e[0]=0;e[1]=1}else if(board[a][c]==7){e[0]=-1;e[1]=-1}else if(board[a][c]==8){e[0]=-1;e[1]=0}else if(board[a][c]==9){e[0]=-1;e[1]=1}return e}
function flip(a,c,e,f,g){if(!(a<1||c<1))if(!(a>=board.length))if(!(c>=board[0].length)){highlight(a,c,g,"rgb(218, 218, 218)");flip(a+e,c+f,e,f,g)}}function highlight(a,c,e,f){if(a!=0)if(c!=0){a=d("r"+a+"c"+c);bg=a.style.backgroundColor;a.style.backgroundColor=e?f:"rgb(255, 255, 255)"}}function isWhite(a,c){bg=d("r"+a+"c"+c).style.backgroundColor;if(!bg)return true;if(""==bg)return true;bg=strip(bg);if("rgb(255,255,255)"==bg)return true;return false}
function animateStart(){animate=true;var a=Math.floor(Math.random()*4);0==a&&animateRandom();1==a&&animateLife();2==a&&animateCycle(true);3==a&&animateCycle(false)}function animateRandom(){animate&&animateSquareToggleTimeout()}function animateSquareToggle(){if(animate){for(var a=Math.floor(Math.random()*50)+1,c=0;c<a;c++){row=randRow();col=randCol();highlight(row,col,isWhite(row,col),"rgb("+randColor()+", "+randColor()+", "+randColor()+")")}animateSquareToggleTimeout()}}
function animateSquareToggleTimeout(){animate&&setTimeout("animateSquareToggle()",randTimeout())}function animateLife(){animate&&animateLifeInit()}var lifeBoard=[];function animateLifeInit(){for(var a=1;a<board.length;a++){lifeBoard[a-1]=[];for(var c=1;c<board[a].length;c++)Math.random()>0.7&&highlight(a,c,true,"rgb(200, 200, 200)")}animateLifeTimeout()}
function animateLifeMain(){for(var a,c,e,f=0;f<board.length-1;f++)for(var g=0;g<board[f].length-1;g++){c=rowFor(f);e=colFor(g);lifeBoard[c][e]=false;a=countLive(c,e);if(isWhite(c+1,e+1)){if(a==2||a==3)lifeBoard[c][e]=true}else if(a==3)lifeBoard[c][e]=true}for(f=0;f<board.length-1;f++)for(g=0;g<board[f].length-1;g++)lifeBoard[f][g]?highlight(f+1,g+1,true,"rgb(200, 200, 200)"):highlight(f+1,g+1,false);animateLifeTimeout()}
function countLive(a,c){var e=0;isWhite(1+rowFor(a-1),1+colFor(c-1))||e++;isWhite(1+rowFor(a-1),1+colFor(c))||e++;isWhite(1+rowFor(a-1),1+colFor(c+1))||e++;isWhite(1+rowFor(a),1+colFor(c-1))||e++;isWhite(1+rowFor(a),1+colFor(c+1))||e++;isWhite(1+rowFor(a+1),1+colFor(c-1))||e++;isWhite(1+rowFor(a+1),1+colFor(c))||e++;isWhite(1+rowFor(a+1),1+colFor(c+1))||e++;return e}function animateLifeTimeout(){animate&&setTimeout("animateLifeMain()",200)}
function animateCycle(a){if(animate){animateCycleInit(a);animateCycleTimeout(a)}}var cycleDirection=[];function animateCycleInit(){for(var a=0;a<board.length-1;a++){cycleDirection[a]=[];for(var c=0;c<board[a].length-1;c++){cycleDirection[a][c]=[true,true,true];highlight(a+1,c+1,true,"rgb(255, 255, 255)")}}}
function animateCycleMain(a){if(animate){for(var c=1;c<=(a?PUZZLE_HEIGHT/2:PUZZLE_HEIGHT);c++)for(var e=1;e<=(a?PUZZLE_WIDTH/2:PUZZLE_WIDTH);e++){var f=rgbValueFor(c,e),g=animateCycleRandDelta(),h=animateCycleRandDelta(),i=animateCycleRandDelta();cycleDirection[c-1][e-1][0]||(g=0-g);cycleDirection[c-1][e-1][1]||(h=0-h);cycleDirection[c-1][e-1][2]||(i=0-i);g=parseInt(rgbR(f))+g;h=parseInt(rgbG(f))+h;f=parseInt(rgbB(f))+i;if(g<0){g=0;cycleDirection[c-1][e-1][0]=true}if(h<0){h=0;cycleDirection[c-1][e-
1][1]=true}if(f<0){f=0;cycleDirection[c-1][e-1][2]=true}if(g>255){g=255;cycleDirection[c-1][e-1][0]=false}if(h>255){h=255;cycleDirection[c-1][e-1][1]=false}if(f>255){f=255;cycleDirection[c-1][e-1][2]=false}highlight(c,e,true,"rgb("+g+", "+h+", "+f+")");if(a){highlight(PUZZLE_HEIGHT-c+1,e,true,"rgb("+g+", "+h+", "+f+")");highlight(PUZZLE_HEIGHT-c+1,PUZZLE_WIDTH-e+1,true,"rgb("+g+", "+h+", "+f+")");highlight(c,PUZZLE_WIDTH-e+1,true,"rgb("+g+", "+h+", "+f+")")}}animateCycleTimeout(a)}}
function animateCycleRandDelta(){return 1+Math.floor(25*Math.random())}function animateCycleTimeout(a){animate&&setTimeout("animateCycleMain("+a+")",100)}function randRow(){return 1+Math.floor(Math.random()*(board.length-1))}function randCol(){return 1+Math.floor(Math.random()*(board[0].length-1))}function randTimeout(){return Math.floor(Math.random()*700+50)}function randColor(){return Math.floor(Math.random()*255)}function randColor100(){return 155+Math.floor(Math.random()*100)}
function satNAll(){for(var a=1;a<board.length;a++)satN(a,a)}function satN(a,c){d("c"+c).className=(stonesCols[c]==board[0][c]?"m":"")+"c"+board[0][c];d("r"+a).className=(stonesRows[a]==board[a][0]?"m":"")+"c"+board[a][0]}function toggle(a,c){togg(a,c,key==16?-1:1,null)}
function togg(a,c,e,f){if(!(blinking||animate)){var g=board[a][c],h;f||undo.push([a,c,0-e]);f=EDIT?cycleEdit:cycle;for(var i=0;i<f.length;i++)if(f[i]==g){g=i+e;if(g==-1)g=f.length-1;else g%=f.length;h=f[g];break}e=board[a][c];if(h==10)g=10;else if(h==5){g=5;if(!EDIT){stonesCols[c]++;stonesRows[a]++}}else if(h==0)g=0;else if(EDIT&&h<14)g=h;else return;board[a][c]=g;eraseCookie("board");createCookie("board",""+board,"30");if(e==5){stonesRows[a]--;stonesCols[c]--}markn&&satN(a,c);arrowsItemsUpdate(e,
g,a,c);updateArrows(false,a,c);if(!EDIT&&doMoves)if(g==0)freeSpots[[a,c]]=[a,c];else e==0&&delete freeSpots[[a,c]];renderCell(a,c);if(!EDIT){findMoves();checkWin()}}}function debug(){}function dumpDebug(){DEBUG&&dumpDebugForce();debughtml=""}function dumpDebugForce(){d("debug").innerHTML=debughtml;debughtml=""}function dump(a){var c="",e;for(e in a)c+="key ["+e+"] val ["+a[e]+"] ";return c}
function performMoves(a,c){for(var e=[],f=0;f<c.length;f++){for(var g=c[f][0],h=c[f][1];board[g][h]!=a;){e[[g,h]]||toggle(g,h);debug("performMoves r"+g+" c"+h+" val "+board[g][h])}if(SYMMETRY_TYPE>-1){e[[g,h]]=[g,h];if(SYMMETRY_TYPE<4)moveChain(e,g,h,a,[SYMMETRY_TYPE]);else if(SYMMETRY_TYPE==4)moveChain(e,g,h,a,[6,6,6]);else if(SYMMETRY_TYPE==5)moveChain(e,g,h,a,[0,1,0]);else if(SYMMETRY_TYPE==6)moveChain(e,g,h,a,[2,3,2]);else if(SYMMETRY_TYPE==7){moveChain(e,g,h,a,[0,1,0]);moveChain(e,g,h,a,[2,3,
2])}}}}function moveChain(a,c,e,f,g){c=[f,c-1,e-1];for(var h,i=0;i<g.length;i++){c=translate(g[i],c[0],c[1],c[2]);e=c[1]+1;h=c[2]+1;if(!a[[e,h]]){for(;!isArrow(e,h)&&board[e][h]!=f;)toggle(e,h);a[[e,h]]=[e,h]}}}
function checkWin(){if(unsolved()==0){!autosolve&&doRender&&win();won=true}else if(emptySquares==0||totalMarbles>=12){var a;if(totalMarbles<12)a="You have only found "+totalMarbles+" of 12 marbles.";else if(totalMarbles>12)a="You have placed "+totalMarbles+" marbles, which is too many.";else if(badMarbles>0)a=badMarbles+" of your marbles "+(badMarbles==1?"is":"are")+" in the wrong spot"+(badMarbles==1?"":"s")+' <a href="javascript:showMe()">(show me)</a>.';d("warn").innerHTML='<img src="warning-32px.jpg"><br>'+
a}else d("warn").innerHTML=""}function win(){reveal();renderSolved();animateStart()}
function renderSolved(){d("c1").className="wins";d("c2").className="wino";d("c3").className="winl";d("c4").className="winv";d("c5").className="wine";d("c6").className="wind";d("c7").className="winx";d("c8").className="winx";d("r1").className="wins";d("r2").className="wino";d("r3").className="winl";d("r4").className="winv";d("r5").className="wine";d("r6").className="wind";d("r7").className="winx";d("r8").className="winx"}
function newGame(a){undo=[];eraseCookie("level");createCookie("level",""+currentBoard,"30");won=animate=EDIT=false;board=makeBoard(a);initStoneCounts();solution=a;if((a=readCookie("board"))&&a!=""){a=a.split(",");for(var c=-1,e=0;e<a.length;e++){e%9==0&&c++;if(c>0&&e%9>0)board[c][e%9]=parseInt(a[e])}}a=readCookie("marka");if(a!=null&&a!="")marka=a=="true"?true:false;a=readCookie("markn");if(a!=null&&a!="")markn=a=="true"?true:false;render();updateArrows(true);updateArrows(false);updateFreeCounts();
findMoves()}function newGameButton(){currentBoard=d("puznum").value-1;newGame(puzzles[currentDifficulty][currentBoard])}
function updateFreeCounts(){freeRows=[];freeCols=[];freeByRow=[];freeByCol=[];for(var a=0;a<board.length;a++)for(var c=0;c<board[0].length;c++)if(c>0&&a>0&&board[a][c]==0&&board[a][0]>0&&board[0][c]>0){if(freeRows[a])freeRows[a]++;else freeRows[a]=1;if(freeCols[c])freeCols[c]++;else freeCols[c]=1;freeByRow[a]||(freeByRow[a]=[]);freeByCol[c]||(freeByCol[c]=[]);freeByRow[a][[a,c]]=[a,c];freeByCol[c][[a,c]]=[a,c]}}
function nameFromDifficulty(){if(currentDifficulty==0)return"easy";if(currentDifficulty==1)return"medium";if(currentDifficulty==2)return"hard";return"unknown"}function newGameRandom(a){eraseCookie("board");currentBoard=Math.floor(Math.random()*puzzles[a].length);currentDifficulty=a;newGame(puzzles[a][currentBoard])}function newGameStart(a){var c=readCookie("level");currentBoard=c&&c!=""?parseInt(c):0;currentDifficulty=a;newGame(puzzles[a][currentBoard])}
function firstPuzzle(){eraseCookie("board");currentBoard=0;newGame(puzzles[currentDifficulty][currentBoard])}function lastPuzzle(){eraseCookie("board");currentBoard=puzzles[currentDifficulty].length-1;newGame(puzzles[currentDifficulty][currentBoard])}function nextPuzzle(){skipPuzzle(1)}function prevPuzzle(){skipPuzzle(puzzles[currentDifficulty].length-1)}
function skipPuzzle(a){eraseCookie("board");currentBoard+=a;currentBoard%=puzzles[currentDifficulty].length;newGame(puzzles[currentDifficulty][currentBoard])}function makeBoard(a){var c=a.length,e=a[0].length;board=Array(c+1);for(var f=0;f<c+1;f++){board[f]=Array(e+1);if(f>0)board[f][0]=countRow(a,f-1)}for(f=0;f<c;f++)for(var g=0;g<e;g++)board[f+1][g+1]=a[f][g]==5?0:a[f][g];for(g=0;g<e;g++)board[0][g+1]=countCol(a,g);return board}
function countRow(a,c){for(var e=0,f=0;f<a[c].length;f++)a[c][f]==5&&e++;return e}function countCol(a,c){for(var e=0,f=0;f<a.length;f++)a[f][c]==5&&e++;return e}function isArrow(a,c){var e=board[a][c];return e>0&&e<10&&e!=5}function isArrowItem(a){return a>0&&a<10&&a!=5}function isFree(a,c){return board[a][c]==0}function isStone(a,c){return board[a][c]==5}function isFilled(a,c){return board[a][c]==10}
function itemName(a){if(a==0)return"free";if(a==5)return"stone";if(a==10)return"filled";return"arrow"}function edit(a){EDIT=true;currentBoard=currentDifficulty=currentLevel=0;board=Array(a+1);for(var c=0;c<board.length;c++){board[c]=Array(a+1);for(var e=0;e<board.length;e++)board[c][e]=0}render();showEditControls()}function showEditControls(){d("editcontrols").style.display=""}
function editShift(a){var c=0,e=0;if(a==0){c=-1;e=0}else if(a==1){c=1;e=0}else if(a==2){c=0;e=-1}else if(a==3){c=0;e=1}a=Array(board.length);for(var f=0;f<board.length;f++){a[f]=Array(board.length);for(var g=0;g<board[f].length;g++)a[f][g]=0}var h,i;for(f=1;f<board.length;f++)for(g=1;g<board[f].length;g++){h=g+c;i=f+e;if(h<1)h=board.length-1;else if(h>board.length-1)h=1;if(i<1)i=board[f].length-1;else if(i>board[f].length-1)i=1;a[i][h]=board[f][g]}for(f=1;f<board.length;f++)for(g=1;g<board[f].length;g++)board[f][g]=
a[f][g];render()}function clearMsg(){d("msg").innerHTML=""}function msg(a){d("msg").innerHTML=a}function d(a){return document.getElementById(a)}function show(a){d(a).style.display=""}function hide(a){d(a).style.display="none"}
function dumpPuzzle(a){for(var c="[",e=0;e<solution.length;e++){c+="[";for(var f=0;f<solution[e].length;f++){c+=a==1?solution[e][f]==5?5:0:a==2?solution[e][f]==11||solution[e][f]!=5&&solution[e][f]>0&&solution[e][f]<10?11:0:solution[e][f];if(f<solution[e].length-1)c+=","}c+="]";if(e<solution.length-1)c+=","}c+="]";return c}
function dumpStones(a){for(var c="[",e=0;e<a.length;e++){c+="[";for(var f=0;f<a[e].length;f++){c+=a[e][f]==5?"5":"0";if(f<a[e].length-1)c+=","}c+="]";if(e<a.length-1)c+=","}c+="]";return c}function smallPuzzle(a){for(var c='<table class="puztable">',e=0;e<a.length;e++){c+='<tr class="puzrow">';for(var f=0;f<a[e].length;f++)c+='<td class="puzcell'+a[e][f]+'"> </td>';c+="</tr>"}c+="</table>";return c}
function dumpSmallPuzzles(a){html="";for(var c=0;c<a.length;c++)html+=c+smallPuzzle(a[c]);d("debug").innerHTML=html}function rowFor(a){var c=board.length-1;a%=c;if(a>=0)return a;return c+a}function colFor(a){var c=board[0].length-1;a%=c;if(a>=0)return a;return c+a}function valOf(a,c){return board[rowFor(a)+1][colFor(c)+1]}function valSet(a,c,e){board[rowFor(a)+1][colFor(c)+1]=e}function rgbR(a){return rgbSplit(a)[0]}function rgbG(a){return rgbSplit(a)[1]}function rgbB(a){return rgbSplit(a)[2]}
function rgbSplit(a){return a.replace("rgb(","").replace(")","").split(",")}function rgbValueFor(a,c){return d("r"+a+"c"+c).style.backgroundColor}function replaceHtml(a,c){var e=typeof a==="string"?document.getElementById(a):a,f=e.cloneNode(false);f.innerHTML=c;e.parentNode.replaceChild(f,e);return f}function strip(a){return a.replace(/ /g,"")}function changepuz(){eraseCookie("board");currentBoard=document.forms[0].puzselect.selectedIndex;newGame(puzzles[currentDifficulty][currentBoard])}
function createCookie(a,c,e){if(e){var f=new Date;f.setTime(f.getTime()+e*24*60*60*1E3);e="; expires="+f.toGMTString()}else e="";document.cookie=a+"="+c+e+"; path=/"}function readCookie(a){a=a+"=";for(var c=document.cookie.split(";"),e=0;e<c.length;e++){for(var f=c[e];f.charAt(0)==" ";)f=f.substring(1,f.length);if(f.indexOf(a)==0)return f.substring(a.length,f.length)}return null}function eraseCookie(a){createCookie(a,"",-1)}function help(){d("help").style.display="";window.location="#help"}
function helpClose(){d("help").style.display="none";window.location="#top"}function options(){document.forms[0].elements.marka.checked=marka;document.forms[0].elements.markn.checked=markn;d("options").style.display=""}function optionsClose(){d("options").style.display="none"}function markaChange(){marka=document.forms[0].elements.marka.checked;createCookie("marka",marka,30);render();options();updateArrows(false)}
function marknChange(){markn=document.forms[0].elements.markn.checked;createCookie("markn",markn,30);render();options();updateArrows(false)}function undoMove(){var a=undo.pop();a&&togg(a[0],a[1],a[2],true)}var blinking=false;function showMe(){blinking=true;setTimeout("showMeBlink(16)",200)}
function showMeBlink(a){if(a==0)blinking=false;else{for(var c=1;c<board.length;c++)for(var e=1;e<board[0].length;e++){b=board[c][e];s=solution[c-1][e-1];b==5&&s!=5&&blinkFlip(c,e)}setTimeout("showMeBlink("+(a-1)+")",200)}}function blinkFlip(a,c){var e=d("r"+a+"c"+c);e.style.display=e.style.display=="none"?"":"none"};
